openapi: 3.0.0
info:
  title: HR
  version: '0.1'
  contact:
    name: OpenDaje
    email: opendaje@example.com
    url: 'https://opendaje-hr.example.com'
  license:
    name: MIT
    url: 'https://github.com/OpenDaje/hr'
  description: HR management
servers:
  - url: 'http://localhost:8080'
    description: Local
paths:
  '/api/users':
    get:
      summary: Get User List
      responses:
        '200':
          description: Users Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: Not Found
      operationId: get-users-list
      description: Retrieve the information of users.
      tags:
        - user

components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      x-examples:
        Joe Doe:
          id: 1
          email: joe.doe@example.com
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
          minimum: 1
          readOnly: true
        email:
          type: string
          format: email
      required:
        - id
        - email
tags:
  - name: user
    description: Operations over users