controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

Iam:
    resource: ../../_iam/src/Adapter/Api/
    type: annotation